//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.dismissingPermissions = new HashSet<dismissingPermission>();
        }
    
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_fax { get; set; }
        public string cust_email { get; set; }
        public string cust_website { get; set; }
        public string cust_phone { get; set; }
        public string cust_mobile { get; set; }
        public string cmp_name { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dismissingPermission> dismissingPermissions { get; set; }
    }
}
