//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class dismissingPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dismissingPermission()
        {
            this.dismissingPermisionProducts = new HashSet<dismissingPermisionProduct>();
        }
    
        public int permission_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> w_id { get; set; }
        public Nullable<System.DateTime> Permission_Date { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dismissingPermisionProduct> dismissingPermisionProducts { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
