//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Contains = new HashSet<Contain>();
            this.dismissingPermisionProducts = new HashSet<dismissingPermisionProduct>();
            this.Product_unit = new HashSet<Product_unit>();
            this.supplyingPermisionProducts = new HashSet<supplyingPermisionProduct>();
        }
    
        public int p_code { get; set; }
        public string p_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<int> expire_duration { get; set; }
        public Nullable<int> w_id { get; set; }
        public Nullable<bool> transfered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contain> Contains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dismissingPermisionProduct> dismissingPermisionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_unit> Product_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyingPermisionProduct> supplyingPermisionProducts { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
