//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_unit
    {
        public int p_code { get; set; }
        public int m_id { get; set; }
        public string dummy { get; set; }
    
        public virtual measureUnit measureUnit { get; set; }
        public virtual product product { get; set; }
    }
}
