//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.supplyingPermissions = new HashSet<supplyingPermission>();
        }
    
        public int sup_id { get; set; }
        public string sup_name { get; set; }
        public string sup_fax { get; set; }
        public string sup_email { get; set; }
        public string sup_website { get; set; }
        public string sup_phone { get; set; }
        public string sup_mobile { get; set; }
        public string cmp_name { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyingPermission> supplyingPermissions { get; set; }
    }
}
