//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplyingPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplyingPermission()
        {
            this.supplyingPermisionProducts = new HashSet<supplyingPermisionProduct>();
        }
    
        public int permission_id { get; set; }
        public Nullable<int> sup_id { get; set; }
        public Nullable<int> w_id { get; set; }
        public Nullable<System.DateTime> permission_date { get; set; }
    
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyingPermisionProduct> supplyingPermisionProducts { get; set; }
        public virtual warehouse warehouse { get; set; }
        public virtual warehouse warehouse1 { get; set; }
    }
}
